# Generated by Django 5.2.8 on 2025-11-19 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy (1-99)'), ('moderate', 'Moderate (1-999)'), ('expert', 'Expert (1-9999)')], max_length=20)),
                ('target_number', models.IntegerField()),
                ('attempts_made', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=10)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('is_won', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.IntegerField()),
                ('attempt_number', models.IntegerField()),
                ('feedback', models.CharField(choices=[('too_high', 'Too High'), ('too_low', 'Too Low'), ('correct', 'Correct')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='games.game')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['user', '-started_at'], name='games_game_user_id_ae000c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['difficulty_level', '-score'], name='games_game_difficu_c9f916_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_won', '-score'], name='games_game_is_won_064987_idx'),
        ),
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['game', 'attempt_number'], name='games_guess_game_id_39059c_idx'),
        ),
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['created_at'], name='games_guess_created_c252a0_idx'),
        ),
    ]
